[development]
address = "0.0.0.0" # 0.0.0.0 address is required for container runtime.
rocksdb_path = "/tmp/habits-service.sst"

[production]
address = "0.0.0.0"
port = 8000
rocksdb_path = "/volumes/rocksdb/habits.sst"
